# -*- coding: utf-8 -*-
"""200866_HW6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EQ3THldZbd5Kyh10ZxQVk6vG-mTk6WsY
"""

# Entrenar un modelo simple para clasificar imágenes de ropa y comparar el
# tiempo que tarda en entrenarse en CPU vs. GPU.

# --- 1. Importar librerías ---
import tensorflow as tf
import time
from tensorflow.keras.datasets import fashion_mnist

#1. Importar la primera (1) base de datos para operar...
print("TensorFlow version:", tf.__version__)
print("GPU disponible:", tf.config.list_physical_devices('GPU'))


#Imágenes que debo transformar
#Nota: las imágenes están conformadas por pixeles de diferentes tipos de gris. Eso es lo que
#se necesita procesar. El modelo con la data procesada le permite leer la distribución de los
#pixeles para detectar la forma y asignarlo a un producto (zapato, vestido, etc). Aquí el
#objetivo.


#2.1 Normalizar para mejor manipulación de data:

(X_train, y_train), (X_test, y_test) = fashion_mnist.load_data()
X_train = X_train / 255.0
X_test = X_test / 255.0

# 3. Entrenamiento en CPU
def crear_modelo():
    model = tf.keras.Sequential([
        tf.keras.Input(shape=(28, 28)),
        tf.keras.layers.Flatten(),
        tf.keras.layers.Dense(128, activation='relu'),
        tf.keras.layers.Dense(10, activation='softmax')
    ])
    model.compile(
        optimizer='adam',
        loss='sparse_categorical_crossentropy',
        metrics=['accuracy']
    )
    return model

# 4. Entrenamiento en GPU (solo si tienes GPU disponible)
print("\n--- Entrenamiento en CPU ---")
with tf.device('/CPU:0'):
    modelo_cpu = crear_modelo()
    start_cpu = time.time()
    modelo_cpu.fit(X_train, y_train, epochs=5, verbose=2)
    end_cpu = time.time()
    print("Tiempo en CPU:", round(end_cpu - start_cpu, 2), "segundos")

#5. Entrenamiento en GPU
if tf.config.list_physical_devices('GPU'):
    print("\n--- Entrenamiento en GPU ---")
    modelo_gpu = crear_modelo()
    with tf.device('/GPU:0'):
        start_gpu = time.time()
        modelo_gpu.fit(X_train, y_train, epochs=5, verbose=2)
        end_gpu = time.time()
        print("Tiempo en GPU:", round(end_gpu - start_gpu, 2), "segundos")
else:
    print(" No se detectó GPU.")

#Parte 2: Toxic Comments

# 1. Dataset Hugging Face

from google.colab import files
uploaded = files.upload()

# 2. Cargar el csv con Pandas y ponerlo en formato Hugging Face para seguir con el formato de la tarea

import pandas as pd

# Carga el archivo CSV
df = pd.read_csv("train.csv")

# Verifica las primeras filas
df.head()

# 3. Preparar el dataset con la clasificación de mensajes:

    # Convertir las etiquetas: 1 si toxicidad ≥ 0.5, 0 si < 0.5
df['toxic'] = (df['toxic'] >= 0.5).astype(int)

    # Eliminar filas con comentarios vacíos (por si acaso)
df = df[df['comment_text'].notnull()]

    # Mostrar muestra
df[['comment_text', 'toxic']].head()

df['toxic'].value_counts()

# 4. Tokenizar

# Por si acaso, descargo librerías...
!pip install transformers datasets --quiet
from transformers import BertTokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')    # el de las indicaciones

# Aplico el tokenizer al subconjunto de datos para entrenar
from datasets import Dataset
import pandas as pd

# archivo ya subido y preprocesado (10,000 filas para que corra)
df = pd.read_csv("train.csv")[["comment_text", "toxic"]].dropna()
df["label"] = (df["toxic"] >= 0.5).astype(int)
df = df[["comment_text", "label"]]
df_small = df.sample(n=10000, random_state=42).reset_index(drop=True)

# Convertimos a formato Hugging Face
dataset = Dataset.from_pandas(df_small)

# Tokenizamos el texto
def tokenize_function(example):
    return tokenizer(example["comment_text"], padding="max_length", truncation=True)

tokenized_dataset = dataset.map(tokenize_function, batched=True)

# 5. Design binary model...
from transformers import AutoModelForSequenceClassification

# Modelo BERT para clasificación binaria (0 = no tóxico, 1 = tóxico)
model = AutoModelForSequenceClassification.from_pretrained("bert-base-uncased", num_labels=2)

print(f"Número total de ejemplos: {len(df)}")

# Argumentos para el entrenamiento:
from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="./results_cpu",     # Carpeta donde se guardan los resultados
    num_train_epochs=2,          # Número de epochs
    per_device_train_batch_size=8,    # Tamaño del batch
    logging_dir="./logs",                 # Carpeta de logs
    logging_steps=10,                     # número de pasos en que se muestra log
)

# 6. Cargar modelo - ENTRENAMIENTO

from transformers import BertForSequenceClassification

# Modelo BERT base para clasificación binaria (2 etiquetas: tóxico o no tóxico)
model = BertForSequenceClassification.from_pretrained("bert-base-uncased", num_labels=2)

## DEF. DEL ENTRENAMIENTO

from transformers import Trainer, TrainingArguments
from transformers import DataCollatorWithPadding

# Asegúrate de que `tokenized_dataset` tenga la columna 'label'
# Dividir el dataset en entrenamiento y evaluación
train_test = tokenized_dataset.train_test_split(test_size=0.2)

# Padding dinámico
data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_test["train"],
    eval_dataset=train_test["test"],
    tokenizer=tokenizer,
    data_collator=data_collator
)

## CPU VS GPU

import time

start = time.time()
trainer.train()
end = time.time()

print(f"Tiempo total de entrenamiento en CPU: {end - start:.2f} segundos")

#a0973a56efed0646f40b3252716b55efe65c8d79

import time

start = time.time()
trainer.train()
end = time.time()

print(f"Tiempo total de entrenamiento en GPU: {end - start:.2f} segundos")